### ISSUE TITLE
High throughput organisering

### ISSUE THREAD

**Issue by lepmik** [CINPLA/AnalysisPipeline#6]
Bør det lages en generisk algoritme for å sende store datamengder gjennom et analysescript?

**Comment by dragly** [comment]
Yes. Let's write one or more packages/scripts that

1) generate experiment files based on raw data and user input
2) read experiment file for further analysis
3) read analysed experiment files and additional files for even further analysis

I suppose point 2) and 3) are what we look for in this issue?
Point 3) is perhaps something to put in an extra package (rather than to have it all in the same, big file).
